modLoader="javafml"
loaderVersion="[45,)"
license="Not specified"

[[mods]]
modId="koftafurniture"
version="1.6.1"
displayName="Kofta Furniture Mod"
credits="Created using mod maker MCreator"
displayURL="https://mcreator.net"
authors="koftatech"
description="This mod adds furniture to minecraft as well as vertical slabs"

[[dependencies.koftafurniture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




